{
 "title": "Dashboard Redes II",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Bytes Transferidos (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(rate(node_network_transmit_bytes_total{job=\"nginx-node\",device=\"eth0\"}[1m]) / (1024*1024), \"servidor\", \"nginx\", \"\", \"\")\nor\nlabel_replace(rate(node_network_transmit_bytes_total{job=\"apache-node\",device=\"eth0\"}[1m]) / (1024*1024), \"servidor\", \"apache\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória RAM (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(process_resident_memory_bytes{job=\"nginx\"} / (1024*1024), \"servidor\", \"nginx\", \"\", \"\") \nor\n label_replace(process_resident_memory_bytes{job=\"apache\"} / (1024*1024), \"servidor\", \"apache\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace((1 - avg(rate(node_cpu_seconds_total{job=\"nginx-node\",mode=\"idle\"}[30s]))) * 100, \"servidor\", \"nginx\", \"\", \"\") \nor \nlabel_replace((1 - avg(rate(node_cpu_seconds_total{job=\"apache-node\",mode=\"idle\"}[30s]))) * 100, \"servidor\", \"apache\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões/Workers Ativos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(nginx_connections_active, \"servidor\", \"nginx\", \"\", \"\") \nor \nlabel_replace(apache_workers{state=\"busy\"}, \"servidor\", \"apache\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Requisições (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "label_replace(rate(nginx_http_requests_total[1m]), \"servidor\", \"nginx\", \"\", \"\") \nor \nlabel_replace(rate(apache_accesses_total[1m]), \"servidor\", \"apache\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "label_replace(nginx_http_requests_total, \"servidor\", \"nginx\", \"\", \"\") or label_replace(apache_accesses_total, \"servidor\", \"apache\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status do Servidor (UP/DOWN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "label_replace(nginx_up, \"servidor\", \"nginx\", \"\", \"\") or label_replace(apache_up, \"servidor\", \"apache\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}