FROM python:3.9

#Instala dependências básicas
RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    curl \
    && rm -rf /var/lib/apt/lists/*

#Cria diretório de trabalho
WORKDIR /app

#Copia apenas os arquivos necessários para o servidor
COPY src/servidor_sequencial.py ./src/
COPY src/configuracao.py ./src/

#Expõe a porta do servidor
EXPOSE 8080

#Comando específico para servidor sequencial
CMD ["python", "src/servidor_sequencial.py"]
